# Generated by Django 2.0.6 on 2018-10-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlistApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaylistSongs',
            new_name='PlaylistSong',
        ),
    ]
