# Generated by Django 2.0.6 on 2018-10-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistApp', '0002_auto_20181010_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsong',
            name='duration',
            field=models.FloatField(),
        ),
    ]
